-- Run this in Supabase SQL Editor before using online/app.js.
create type public.user_role as enum ('admin', 'sales_agent');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Team member',
  role public.user_role not null default 'sales_agent',
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  acronym text not null,
  barcode text unique not null,
  category text not null default 'General',
  stock integer not null default 0 check (stock >= 0),
  reorder_level integer not null default 5 check (reorder_level >= 0),
  cost numeric(12,2) not null default 0,
  price numeric(12,2) not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);

create table public.sales (
  id bigint generated by default as identity primary key,
  receipt_no text unique not null,
  product_id bigint not null references public.products(id),
  agent_id uuid not null references public.profiles(id),
  agent_name text not null,
  qty integer not null check (qty > 0),
  total numeric(12,2) not null,
  profit numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into public.profiles (id, full_name, role) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'Team member'), 'sales_agent'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
create policy "users read own profile" on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy "authenticated users read products" on public.products for select to authenticated using (true);
create policy "admins manage products" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins read all sales" on public.sales for select to authenticated using (public.is_admin() or agent_id = auth.uid());
create policy "agents create sales" on public.sales for insert to authenticated with check (agent_id = auth.uid());

insert into public.products (name, acronym, barcode, category, stock, reorder_level, cost, price) values
('Front brake pads', 'FBP', '600100100001', 'Braking', 28, 8, 24, 39.90),
('Engine oil 5W-30', 'OIL', '600100100002', 'Lubricants', 46, 12, 18, 29.50),
('Spark plugs', 'SPK', '600100100003', 'Ignition', 64, 16, 6.50, 12.90),
('Air filter', 'AF', '600100100004', 'Filters', 8, 10, 11, 21.50),
('Wiper blades 22 inch', 'WB22', '600100100005', 'Visibility', 7, 10, 8, 16.50),
('Battery 12V 60Ah', 'BAT60', '600100100006', 'Electrical', 3, 5, 72, 109.00);

-- After creating the administrator account in Supabase Auth, run:
-- update public.profiles set role = 'admin', full_name = 'Amina M.' where id = 'YOUR_ADMIN_USER_UUID';
