-- Run this in Supabase SQL Editor before using online/app.js.
do $$
begin
  if not exists (
    select 1
    from pg_type type_record
    join pg_namespace namespace_record on namespace_record.oid = type_record.typnamespace
    where type_record.typname = 'user_role'
      and namespace_record.nspname = 'public'
  ) then
    create type public.user_role as enum ('admin', 'sales_agent');
  end if;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Team member',
  role public.user_role not null default 'sales_agent',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  acronym text not null,
  barcode text unique not null,
  category text not null default 'General',
  stock integer not null default 0 check (stock >= 0),
  reorder_level integer not null default 5 check (reorder_level >= 0),
  cost numeric(12,2) not null default 0,
  price numeric(12,2) not null default 0,
  supplier text,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  receipt_no text unique not null,
  product_id bigint not null references public.products(id),
  agent_id uuid not null references public.profiles(id),
  agent_name text not null,
  qty integer not null check (qty > 0),
  total numeric(12,2) not null,
  profit numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.returns (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  receipt_no text,
  agent_id uuid not null references public.profiles(id),
  agent_name text not null,
  qty integer not null check (qty > 0),
  type text not null check (type in ('Return', 'Warranty')),
  reason text not null,
  notes text,
  status text not null default 'Open' check (status in ('Open', 'Approved', 'Rejected', 'Resolved')),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into public.profiles (id, full_name, role) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', 'Team member'), 'sales_agent'); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.returns enable row level security;
drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists "authenticated users read products" on public.products;
create policy "authenticated users read products" on public.products for select to authenticated using (true);
drop policy if exists "admins manage products" on public.products;
create policy "admins manage products" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins read all sales" on public.sales;
create policy "authenticated users read all sales" on public.sales for select to authenticated using (true);
drop policy if exists "agents create sales" on public.sales;
drop policy if exists "agents create returns" on public.returns;
drop policy if exists "admins read all returns" on public.returns;
create policy "authenticated users read all returns" on public.returns for select to authenticated using (true);
drop policy if exists "admins manage returns" on public.returns;
create policy "admins manage returns" on public.returns for update to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.record_return(
  p_product_id bigint,
  p_receipt_no text,
  p_qty integer,
  p_type text,
  p_reason text,
  p_notes text default null
)
returns public.returns
language plpgsql
security definer
set search_path = public
as $$
declare
  sale_total integer;
  agent_profile public.profiles;
  return_record public.returns;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_qty is null or p_qty <= 0 or p_qty <> trunc(p_qty) then raise exception 'Quantity must be a positive whole number'; end if;
  if p_type not in ('Return', 'Warranty') then raise exception 'Invalid return type'; end if;
  if length(trim(coalesce(p_reason, ''))) < 2 then raise exception 'A return reason is required'; end if;

  select * into agent_profile from public.profiles where id = auth.uid();
  if agent_profile.id is null then raise exception 'Profile not found'; end if;
  if p_receipt_no is not null then
    select coalesce(sum(qty), 0) into sale_total from public.sales where receipt_no = p_receipt_no and product_id = p_product_id and (public.is_admin() or agent_id = auth.uid());
    if sale_total < p_qty then raise exception 'Return quantity exceeds the recorded sale'; end if;
  end if;

  insert into public.returns (product_id, receipt_no, agent_id, agent_name, qty, type, reason, notes)
  values (p_product_id, nullif(trim(p_receipt_no), ''), auth.uid(), agent_profile.full_name, p_qty, p_type, trim(p_reason), nullif(trim(p_notes), ''))
  returning * into return_record;
  return return_record;
end;
$$;

revoke all on function public.record_return(bigint, text, integer, text, text, text) from public;
grant execute on function public.record_return(bigint, text, integer, text, text, text) to authenticated;

create or replace function public.record_sale(
  p_product_id bigint,
  p_qty integer,
  p_sale_price numeric default null
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_product public.products;
  agent_profile public.profiles;
  final_price numeric(12,2);
  sale_record public.sales;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_qty is null or p_qty <= 0 then raise exception 'Quantity must be greater than zero'; end if;
  if p_qty <> trunc(p_qty) then raise exception 'Quantity must be a whole number'; end if;

  select * into agent_profile from public.profiles where id = auth.uid();
  if agent_profile.id is null then raise exception 'Profile not found'; end if;

  select * into selected_product from public.products where id = p_product_id for update;
  if selected_product.id is null then raise exception 'Product not found'; end if;
  if selected_product.stock < p_qty then raise exception 'Insufficient stock'; end if;
  final_price := coalesce(p_sale_price, selected_product.price);
  if final_price < selected_product.cost then raise exception 'Selling price cannot be below incoming cost'; end if;

  update public.products set stock = stock - p_qty where id = selected_product.id;
  insert into public.sales (receipt_no, product_id, agent_id, agent_name, qty, total, profit)
  values (
    'SL-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS') || '-' || lpad((floor(random() * 1000))::text, 3, '0'),
    selected_product.id, auth.uid(), agent_profile.full_name, p_qty,
    round(final_price * p_qty, 2), round((final_price - selected_product.cost) * p_qty, 2)
  ) returning * into sale_record;
  return sale_record;
end;
$$;

revoke all on function public.record_sale(bigint, integer, numeric) from public;
grant execute on function public.record_sale(bigint, integer, numeric) to authenticated;

-- Run this separately if the products table already exists from an earlier setup.
alter table public.products add column if not exists supplier text;

-- Product image storage for the optional image-file field.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "authenticated users read product images" on storage.objects;
create policy "authenticated users read product images" on storage.objects
for select to authenticated using (bucket_id = 'product-images');
drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());
drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects
for update to authenticated using (bucket_id = 'product-images' and public.is_admin()) with check (bucket_id = 'product-images' and public.is_admin());

insert into public.products (name, acronym, barcode, category, stock, reorder_level, cost, price) values
('Front brake pads', 'FBP', '600100100001', 'Braking', 28, 8, 24, 39.90),
('Engine oil 5W-30', 'OIL', '600100100002', 'Lubricants', 46, 12, 18, 29.50),
('Spark plugs', 'SPK', '600100100003', 'Ignition', 64, 16, 6.50, 12.90),
('Air filter', 'AF', '600100100004', 'Filters', 8, 10, 11, 21.50),
('Wiper blades 22 inch', 'WB22', '600100100005', 'Visibility', 7, 10, 8, 16.50),
('Battery 12V 60Ah', 'BAT60', '600100100006', 'Electrical', 3, 5, 72, 109.00)
on conflict (barcode) do nothing;

-- After creating the administrator account in Supabase Auth, run:
-- update public.profiles set role = 'admin', full_name = 'Amina M.' where id = 'YOUR_ADMIN_USER_UUID';
